#SpringBoot整合MyBatis框架
#1.加载MyBatis配置文件
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: pp.pokemon.pm.entity
#2.数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pmlgpe?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
